name: Attest Build Provenance

on:
  workflow_dispatch:

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/attest-build-provenance@v3
        with:
          # Path to the artifact serving as the subject of the attestation. Must
          # specify exactly one of "subject-path", "subject-digest", or
          # "subject-checksums". May contain a glob pattern or list of paths
          # (total subject count cannot exceed 1024).
          subject-path:

          # SHA256 digest of the subject for the attestation. Must be in the form
          # "sha256:hex_digest" (e.g. "sha256:abc123..."). Must specify exactly one
          # of "subject-path", "subject-digest", or "subject-checksums".
          subject-digest:

          # Subject name as it should appear in the attestation. Required when
          # identifying the subject with the "subject-digest" input.
          subject-name:

          # Path to checksums file containing digest and name of subjects for
          # attestation. Must specify exactly one of "subject-path", "subject-digest",
          # or "subject-checksums".
          subject-checksums:

          # Whether to push the attestation to the image registry. Requires that the
          # "subject-name" parameter specify the fully-qualified image name and that
          # the "subject-digest" parameter be specified. Defaults to false.
          push-to-registry:

          # Whether to attach a list of generated attestations to the workflow run
          # summary page. Defaults to true.
          show-summary:

          # The GitHub token used to make authenticated API requests. Default is
          #  ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}