name: Attest Build Provenance

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build artifact
        run: |
          mkdir -p dist
          echo "hello world" > dist/my-app.zip

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'dist/my-app.zip'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-to-registry: false
          show-summary: true