name: Remover Workflow Runs

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Deletar todos os workflow runs (exceto o atual)
        run: |
          REPO="spacedwog/Hive"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CURRENT_RUN_ID="215"

          echo "Repositório: $REPO"
          echo "Run atual: $CURRENT_RUN_ID"

          # Busca todos os workflow runs (últimos 100)
          runs=$(curl -s -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/actions/runs?per_page=100")

          # Verifica se retornou algo
          if [ "$(echo "$runs" | jq '.workflow_runs | length')" -eq 0 ]; then
            echo "Nenhum workflow run encontrado."
            exit 0
          fi

          # Percorre todos os IDs dos runs e deleta
          echo "$runs" | jq -r '.workflow_runs[].id' | while read run_id; do
            if [ "$run_id" != "$CURRENT_RUN_ID" ]; then
              echo "Deletando run $run_id..."
              curl -s -X DELETE \
                -H "Authorization: Bearer $TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            else
              echo "Ignorando o run atual $run_id"
            fi
          done